### ISSUE TITLE
Sometimes the copy button obscures demo code text

### ISSUE THREAD

**Issue by cdata** [PolymerElements/iron-demo-helpers#15]
Example:

![image](https://cloud.githubusercontent.com/assets/240083/13122558/5bdf3048-d56c-11e5-8267-d284bdb58420.png)

The correct resolution is probably a matter of subjective opinion, but as implemented it is kind of messy looking.

**Comment by notwaldorf** [comment]
Oh, yup. I can either add a top padding or a right padding. On it.
