### ISSUE TITLE
code is not colored with dom=shadow

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-demo-helpers#28]
When in `dom='shadow'` mode, the code part doesn't get awesomely colored :c
http://jsbin.com/xasabi/1/edit?html,output
![screen shot 2016-04-11 at 3 41 49 pm](https://cloud.githubusercontent.com/assets/6173664/14444735/60d842aa-fffc-11e5-9009-e72395478fe3.png)
![screen shot 2016-04-11 at 3 41 40 pm](https://cloud.githubusercontent.com/assets/6173664/14444736/60d9b69e-fffc-11e5-8042-efc18df0e314.png)

**Comment by notwaldorf** [comment]
This is a `prism-highlighter` issue. I thought an issue was already opened, but couldn't find one, so: https://github.com/PolymerElements/prism-element/issues/14
