### ISSUE TITLE
Does not render when it is inside of any template tag

### ISSUE THREAD

**Issue by beatbits** [PolymerElements/iron-demo-helpers#29]
### Description

Demo-snippet does not render when it is inside a template tag
### Expected outcome

To be rendered as normal
### Actual outcome

The demo seems to be empty
### Live Demo

http://jsbin.com/wamemofewi/edit?html,output
### Steps to reproduce
1. Put a `demo-snippet` element inside any template tag
2. See it does not render properly
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [ ] Edge (I bet yes)
- [ ] IE 11 (I bet yes)
- [ ] IE 10 (I bet yes)

**Comment by carolirod** [comment]
+1

**Comment by cells-developers** [comment]
+1

**Comment by abdonrd** [comment]
+1

**Comment by NicolasRannou** [comment]
+1

**Comment by mgibas** [comment]
+1

**Comment by notwaldorf** [comment]
Yeah, I think this is a problem with how we stamp the inner template. If anyone wants to take a stab at debugging this, it would be much appreciated.

**Comment by sasivarnan** [comment]
+1

**Comment by themes-lab** [comment]
+1

**Comment by themes-lab** [comment]
Hi,

I found a solution to display demo-helpers inside template tags:

1) Remove template tag inside demo-snippet, for example it will look like that:
```
<demo-snippet class="centered-demo">
  <input type="date"> 
</demo-snippet>
```

2) Edit attached callback in iron-demo-helpers/demo-snippet.html like this:
```
attached: function() {
  var content = this.getContentChildren('#content')[0],
  parent = content.parentNode,
  contents = parent.innerHTML ;
  // If there's no template, render empty code.
  if (!content) {
    this._markdown = '```\n```';
    return;
  }
  var snippet = this.$.marked.unindent(contents);
  // Boolean properties are displayed as checked="", so remove the ="" bit.
  snippet = snippet.replace(/=""/g, '');
  this._markdown = '```\n' + snippet + '\n' + '```';
},
```

Hope this will help :-)

Mickael

**Comment by motss** [comment]
+1

**Comment by mercmobily** [comment]
#32 fixes this -- beautifully, with one tiny change, and providing tests for it. Please review that patch and merge it -- data binding is so important for demos!

**Comment by motss** [comment]
#32 should be merged! :laughing:

**Comment by mercmobily** [comment]
I just noticed that the bower version of the widget still doesn't include this veeeery important patch. I don't suppose you could create a git tag for it, so that it becomes available without tinkering? Thank you!

**Comment by notwaldorf** [comment]
This has already been released as `v1.2.4`

**Comment by notwaldorf** [comment]
Closing as fixed in #32

**Comment by carolirod** [comment]
I think is not yet fully fixed? Cause #32 fixed this case:

```html
<demo-snippet>
    <template is="dom-bind">
        <input type="date" value="{{dateValue}}">
    </template>
</demo-snippet>
```

but not this one (which was the original posted issue: http://jsbin.com/wamemofewi/edit?html,output):

```html
<template is="dom-bind" id="demo">
   <demo-snippet>
      <template>
        <input type="date" value="{{dateValue}}">
      </template>
   </demo-snippet>
</template>
```

**Comment by notwaldorf** [comment]
I'll re-open it, but I would recommend jut re-jiggering the order of your templates, since that works

**Comment by mercmobily** [comment]
My humble 2c.
I would frankly keep this closed. The use case in the original ticket
wanted to be able to use `<template dom-bind>` around the demos. However,
each demo should be independent. So, I am not sure there is a sane use case
for this... Unless the fix is a one liner!

**Comment by carolirod** [comment]
@mercmobily okay, let's keep it close then.

**Comment by samiheikki** [comment]
+1.

Wanted to create a `<demo-component>` Polymer Element, but can't use `<demo-snippet>` because it's inside the `<demo-component>`'s template.

**Comment by alvaropinot** [comment]
+1

**Comment by notwaldorf** [comment]
Closing following the user feedback to close it :D

**Comment by samiheikki** [comment]
My +1 was not an indicator to close this, but to fix this 😞

**Comment by alvaropinot** [comment]
reopen this please :D

**Comment by mercmobily** [comment]
@samiheikki @alvaropinot  What are your use cases?

**Comment by samiheikki** [comment]
@mercmobily see https://github.com/PolymerElements/iron-demo-helpers/issues/29#issuecomment-265970584

**Comment by samiheikki** [comment]
Please re-open :)

**Comment by samiheikki** [comment]
Hello?

**Comment by iSuslov** [comment]
+1 not working in Polymer 2.0

**Comment by aigan** [comment]
I got it to work in Polymer 2 by setting the template in `_updateMarkdown` to `this`. That made it work with
```html
<dom-bind>
	<template>
		<demo-snippet class="centered-demo">
			... demo code here ...
		</demo-snippet>
	</template>
</dom-bind>
```

**Comment by intcreator** [comment]
@aigan thanks to you I was able to get the rendered code to display, but I'm still having issues with the code.  I get the following error:
```
Malformed syntax-highlight event: {code: "", lang: undefined}

(legacy-element-mixin.html:918)
```
The code does not appear on the page inside the `marked-element` slot.  Is this related to stamping or is it a different issue?  I'm using Polymer 2 and I'm putting `demo-snippet` elements inside one of my custom elements.  I'm having a lot of issues with the `demo-snippet` element rendering something useful.

**Comment by AStaroverov** [comment]
Doesnt work for me too :(

**Comment by samiheikki** [comment]
Luckily this works in https://github.com/vaadin/vaadin-demo-helpers

**Comment by intcreator** [comment]
@mercmobily I'm also trying to simply embed some `<demo-snippet>` elements in my Polymer app (which means they need to be inside of the `<template>` tag for the custom element I place them in).  I'm making a tutorial and I'm using pre-made elements for rendering Markdown and routing.  I don't think including some copyable code snippet demos is an insane use case.  I don't even need bindings—I just need to render vanilla HTML tags!

**Comment by sandro-k** [comment]
@intcreator you get around

```
Malformed syntax-highlight event: {code: "", lang: undefined}

(legacy-element-mixin.html:918)
``` 

by placing `preserve-content` on the `template` tag like. 

```
<demo-snippet>
    <template preserve-content>
      <p>Demo</p>
    </template>
</demo-snippet>
```

Still I am not able to dynamically update my demo like shown in the original demo.

**Comment by renfeng** [comment]
I've been reading pull request #32, issue #31, #30, and this one for hours... trying to figure out how to make data binding work for my ```<demo-snippet>```. For anyone who comes here just for a quick answer, here is an example.
http://jsbin.com/ruzivequha/edit?html,output

I'm thankful to find my answer.
https://www.webcomponents.org/element/renfeng/d3-colony/demo/demo/index.html

The sample code provided by @carolirod doesn't work any more.
```
<demo-snippet>
    <template is="dom-bind">
        <input type="date" value="{{dateValue}}">
    </template>
</demo-snippet>
```

Here's a discussion on short hand form (```is="dom-xxx"```) vs native element (```<dom-xxx>```)
https://github.com/Polymer/docs/issues/2428

Close, or not to close this issue... is a question. @mercmobily @notwaldorf

**Comment by yveslange** [comment]
Any update ? I was still hoping a solution on that.

**Comment by intcreator** [comment]
I made [my own custom lit-html element](https://github.com/intcreator/code-demo) for now.
