### ISSUE TITLE
"Help": Custom CSS properties strangely overwriting themselves in simple demo

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/iron-demo-helpers#36]
Disclaimer: this is probably my fault. I think. I posted it on StackOverflow, but it's sooOOOoo specific I doubt anybody will even have a look...

I wrote a really [simple element to validate a form](https://github.com/mercmobily/hot-form-validator/tree/v0.1.3), and wrote full demo for it. To see it, just do `bower install hot-form-validator`, go into `bower_components/hot-form-validator`, run ``bower install` again for devDependencies,   and see the demo with `polymer serve`.

I am having a strange issue, as in the demo the paper-toast are coming out in the wrong color.

Here is the source of the demo. Please only consider the first three snippets. Look at line 88, 119 and 149. 

It seems like only the last setting of the property is taken. However, since the target of the rule is a Polymer element, it should be ale to hold the value...

What am I doing wrong?
In theory, from my understanding of custom CSS properties, first of all I set some variable in `:root` within `<head>`:

    <head>
      <style is="custom-style" include="demo-pages-shared-styles">

        :root {
            paper-toast {
              --paper-toast-background-color: green;
              --paper-toast-color: white;
            };
            paper-toast#secondGlobalToast {
              --paper-toast-background-color: blue;
              --paper-toast-color: white;
            };
            paper-toast#errorGlobalToast {
              --paper-toast-background-color: red;
              --paper-toast-color: white;
            };
          }

        </style>
      
So,  `--paper-toast-background-color` and  `--paper-toast-color` are set in the "root" scope of the custom properties.

Then, for a snippet:

          <demo-snippet>
            <template>

              <style is="custom-style">
                  paper-toast {
                    --paper-toast-background-color: white; /* This is overwritten by line 149?!? */
                    --paper-toast-color: white;
                  };
                  paper-toast#errorToast {
                    --paper-toast-background-color: red;
                    --paper-toast-color: white;
                  };
              </style>

Here, `--paper-toast-background-color` and  `--paper-toast-color` should be set in the scope of the targeted components. And yet, line 149 seems to be rewriting both of them.

It's not even a shim limitation issue: if you run this with native CSS properties, the same thing happens. So, I must have misunderstood how these are scoped.

Help? I am supposed to hand this in tomorrow, and I just don't know what to do.

    <!doctype html>
    <html>
      <head>
        <title>hot-form-validator demo</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
        <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

        <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">
        <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">

        <link rel="import" href="../hot-form-validator.html">

        
        <link rel="import" href="../../iron-form/iron-form.html">
        <link rel="import" href="../../paper-input/paper-input.html">
        <link rel="import" href="../../paper-toast/paper-toast.html">
        <link rel="import" href="../../paper-button/paper-button.html">
        <link rel="import" href="../../iron-ajax/iron-ajax.html">
        <script src="../../sinonjs/sinon.js"></script>

        <style is="custom-style" include="demo-pages-shared-styles">

          :root {
            paper-toast {
              --paper-toast-background-color: green;
              --paper-toast-color: white;
            };
            paper-toast#secondGlobalToast {
              --paper-toast-background-color: blue;
              --paper-toast-color: white;
            };
            paper-toast#errorGlobalToast {
              --paper-toast-background-color: red;
              --paper-toast-color: white;
            };
          }

        </style>
      </head>
      <body>

        <paper-toast id="firstGlobalToast"></paper-toast>
        <paper-toast id="secondGlobalToast" class="second"></paper-toast>
        <paper-toast class="error" id="errorGlobalToast"></paper-toast>

        <script>
          sinon.log = function( m ){console.log("Message:", m)};
          //var server = sinon.useFakeXMLHttpRequest()
          server = sinon.fakeServerWithClock.create();
          //server.autoRespond = true;
          server.respondImmediately = true;

          server.respondWith(
            'POST',
            'submit_validating', [
              200,
              'application/json',
              '{"name":"nameField","surname":"surnameField"}'
            ]
          );

          server.respondWith(
            'POST',
            'submit_not_validating', [
              422,
              'application/json',
              '{"message":"Unprocessable Entity","errors":[{"field":"maker","message":"Maker is not acceptable"}]}'
            ]
          );
        </script>

        <h1>Local toasts</h1>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, passing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">
                  paper-toast {
                    --paper-toast-background-color: white; /* This is overwritten by line 149?!? */
                    --paper-toast-color: white;
                  };
                  paper-toast#errorToast {
                    --paper-toast-background-color: red;
                    --paper-toast-color: white;
                  };
              </style>

              <hot-form-validator sane-submit error-toast-id="errorToast">
                <paper-toast id="firstToast"></paper-toast>
                <paper-toast id="errorToast"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, failing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">
                  paper-toast {
                    --paper-toast-background-color: green;
                    --paper-toast-color: white;
                  };
                  paper-toast#errorToast {
                    --paper-toast-background-color: red; /* This is overwritten by line 149?!? */
                    --paper-toast-color: white;
                  };
              </style>

              <hot-form-validator sane-submit error-toast-id="errorToast">
                <paper-toast id="firstToast"></paper-toast>
                <paper-toast id="errorToast"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_not_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using specified toast element, passing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">
                  paper-toast {
                    --paper-toast-background-color: gray; /* THIS influences line 119 */
                    --paper-toast-color: white;
                  };
                  paper-toast#secondToast {
                    --paper-toast-background-color: blue;
                    --paper-toast-color: white;
                  };
                  paper-toast.errorToast {
                    --paper-toast-background-color: purple;
                    --paper-toast-color: white;
                  };
              </style>

              <hot-form-validator sane-submit toast-id="secondToast" error-toast-id="errorToast">
                <paper-toast id="firstToast"></paper-toast>
                <paper-toast id="secondToast"></paper-toast>
                <paper-toast id="errorToast"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <h1>Global toasts</h1>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using global toast element, passing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using global toast element, failing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_not_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using specified global toast element, passing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast toast-id="secondGlobalToast" error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

      </body>
    </html>

**Comment by mercmobily** [comment]
Wait a second. I somehow assumed that <template> signified the creation of a shadow root. However, I am starting to think that I am wrong. I also noticed that `<style is="custom-style">` in `<template>`, instead of just `<style>`.

I must renamed my IDs so that they don't clash, and everything seems to be working (!).
Does that mean that anything within a `<template>` doesn't get its own CSS scoping like it happens when I create a "proper" Polymer element? (that is, an element with a Shadow root attached to it...)

    <!doctype html>
    <html>
      <head>
        <title>hot-form-validator demo</title>

        <script>
          window.Polymer = { lazyRegister: false, dom: 'shadow', useNativeCSSProperties: true };
        </script>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
        <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

        <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">
        <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">

        <link rel="import" href="../hot-form-validator.html">

        
        <link rel="import" href="../../iron-form/iron-form.html">
        <link rel="import" href="../../paper-input/paper-input.html">
        <link rel="import" href="../../paper-toast/paper-toast.html">
        <link rel="import" href="../../paper-button/paper-button.html">
        <link rel="import" href="../../iron-ajax/iron-ajax.html">
        <script src="../../sinonjs/sinon.js"></script>

        <style is="custom-style" include="demo-pages-shared-styles">

          :root {
            paper-toast {
              --paper-toast-background-color: green;
              --paper-toast-color: white;
            };
            paper-toast#secondGlobalToast {
              --paper-toast-background-color: blue;
              --paper-toast-color: white;
            };
            paper-toast#errorGlobalToast {
              --paper-toast-background-color: red;
              --paper-toast-color: white;
            };
          }

        </style>
      </head>
      <body>

        <paper-toast id="firstGlobalToast"></paper-toast>
        <paper-toast id="secondGlobalToast"></paper-toast>
        <paper-toast id="errorGlobalToast"></paper-toast>


        <script>
          sinon.log = function( m ){console.log("Message:", m)};
          //var server = sinon.useFakeXMLHttpRequest()
          server = sinon.fakeServerWithClock.create();
          //server.autoRespond = true;
          server.respondImmediately = true;

          server.respondWith(
            'POST',
            'submit_validating', [
              200,
              'application/json',
              '{"name":"nameField","surname":"surnameField"}'
            ]
          );

          server.respondWith(
            'POST',
            'submit_not_validating', [
              422,
              'application/json',
              '{"message":"Unprocessable Entity","errors":[{"field":"maker","message":"Maker is not acceptable"}]}'
            ]
          );
        </script>

        <h1>Local toasts</h1>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, passing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">
                paper-toast#errorToast1 {
                  --paper-toast-background-color: red;
                  --paper-toast-color: white;
                };

                paper-toast#firstToast1 {
                  --paper-toast-background-color: white; /* This is overwritten by line 149?!? */
                  --paper-toast-color: white;
                };

              </style>

              <hot-form-validator sane-submit error-toast-id="errorToast1">
                <paper-toast id="firstToast1"></paper-toast>
                <paper-toast id="errorToast1"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>


        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, failing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">

                paper-toast#errorToast2 {
                  --paper-toast-background-color: red; /* This is overwritten by line 149?!? */
                  --paper-toast-color: white;
                };

                paper-toast#firstToast2 {
                  --paper-toast-background-color: green;
                  --paper-toast-color: white;
                };
              </style>

              <hot-form-validator sane-submit error-toast-id="errorToast2">
                <paper-toast id="firstToast2"></paper-toast>
                <paper-toast id="errorToast2"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_not_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using specified toast element, passing</h3>
          <demo-snippet>
            <template>

              <style is="custom-style">
                  paper-toast#secondToast3 {
                    --paper-toast-background-color: blue;
                    --paper-toast-color: white;
                  };
                  paper-toast#errorToast3 {
                    --paper-toast-background-color: purple;
                    --paper-toast-color: white;
                  };
                  paper-toast#firstToast3 {
                    --paper-toast-background-color: gray; /* THIS influences line 119 */
                    --paper-toast-color: white;
                  };

              </style>

              <hot-form-validator sane-submit toast-id="secondToast3" error-toast-id="errorToast3">
                <paper-toast id="firstToast3"></paper-toast>
                <paper-toast id="secondToast3"></paper-toast>
                <paper-toast id="errorToast3"></paper-toast>
                <form id="form" is="iron-form" method="POST" action="submit_not_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <h1>Global toasts</h1>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using global toast element, passing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using global toast element, failing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_not_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

        <div class="vertical-section-container centered">
          <h3>Basic hot-form-validator, using specified global toast element, passing</h3>
          <demo-snippet>
            <template>

              <hot-form-validator sane-submit global-toast toast-id="secondGlobalToast" error-toast-id="errorGlobalToast">
                <form id="form" is="iron-form" method="POST" action="submit_validating">
                  <paper-input name="maker" id="maker" ></paper-input>
                  <paper-input name="model" id="model"></paper-input>
                  <paper-button type="submit" raised>Submit!</paper-button>
                </form>
              </hot-form-validator>

            </template>
          </demo-snippet>
        </div>

      </body>
    </html>

**Comment by mercmobily** [comment]
I had to take out `root:` from `<head>` to make things work properly for the global toasts too. Can somebody _please_ pretty please explain to be why that is? I am obviously missing important bits and pieces here...

**Comment by notwaldorf** [comment]
A `<template>` doesn't have a shadow root, so there's no encapsulation you get for free -- it's just an inactive element. `demo-snippet` finds its nested template and stamps it. They all live in the same scope, so styles will be overwritten (you can see that by using two demo-snippets that both style the same id: http://jsbin.com/guqawax/edit?html,output).

**Comment by mercmobily** [comment]
I imagined as much. Ta!
