### ISSUE TITLE
No longer need to place the code in a template

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/iron-demo-helpers#38]
It would make sense to use demo-snippet without wrapping or code in a `<template>` as long as we don't want the "dom-bind" feature.

**Comment by notwaldorf** [comment]
If you don't pass a `template` to `demo-snippet`, then the elements contained (and the `style` tag) will already be stamped by the time `demo-snippet` gets to it -- so the code being displayed will be the post-stamping code, which may not be the code you initially typed out.
