### ISSUE TITLE
Scroll position is lost after refresh

### ISSUE THREAD

**Issue by limonte** [PolymerElements/iron-demo-helpers#45]
### Description
Scroll posistion of https://elements.polymer-project.org/bower_components/iron-demo-helpers/demo/index.html is lost after page refresh. For instance, I scroll to the bottom page and hit Refresh button.

### Expected outcome
After refresh page is scrolled to the bottom, exactly to the same position as it was before refresh. 

### Actual outcome
After refresh page is scrolled to the 20-30% of the page height. 

### Live Demo
https://elements.polymer-project.org/bower_components/iron-demo-helpers/demo/index.html
![recorded](https://cloud.githubusercontent.com/assets/6059356/20526700/dbe59722-b0cd-11e6-8851-caa7cdb01596.gif)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
`iron-demo-helpers` is just a small element that displays a demo. It does not keep track of the scroll position in the page, as that's a thing that the app/page that uses it should do

**Comment by notwaldorf** [comment]
That's maybe an issue better opened on https://github.com/Polymer/polymer-element-catalog
