### ISSUE TITLE
[2.0-preview] No code syntax colors. 

### ISSUE THREAD

**Issue by tur-nr** [PolymerElements/iron-demo-helpers#55]
### Description
`demo-snippet` has no color syntax for the code inside the `template`.

### Expected outcome
Code inside the `template` of a `demo-snippet` should have correct syntax coloring.

### Actual outcome
Code is formatted to fixed width with no colors.

### Live Demo
![demo](http://i.imgur.com/XcFKFew.png)

### Steps to reproduce

1. `$ mkdir demo && cd $_`
2. `$ yarn add polymer-cli bower`
3. `$ bower install polymer@^2.0.0-rc.3 iron-demo-helpers@2.0-preview`
4. `$ mkdir demo`
5. `$ touch demo/index.html`
6. Save the following to `demo/index.html`

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
    
    <title>Demo</title>
    
    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

    <link rel="import" href="../../polymer/polymer.html">
    <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">
    <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">

    <custom-style>
      <style is="custom-style" include="demo-pages-shared-styles"></style>
    </custom-style>
  </head>
  <body unresolved>
    <div class="centered">
      <h4>Demo</h4>
      <demo-snippet>
        <template>
          <script type="text/javascript">
            console.log('Hello, World!');
          </script>
          <style>
            my-element {
              background: red;
            }
          </style>
          <my-element attr="something"></my-element>
        </template>
      </demo-snippet>
    </div>
  </body>
</html>
```
7. `$ polymer serve`
8. Open browser to http://localhost:8080/components/demo/demo/index.html

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Fixed in 67e289c
