### ISSUE TITLE
Missing bower dependency for font-roboto/roboto.html

### ISSUE THREAD

**Issue by mattpalermo** [PolymerElements/iron-demo-helpers#61]
I noticed that the demo page generated by the polymer-cli for a polymer 2 element throws an error: 

```
Failed to load resource: http://127.0.0.1:8081/components/font-roboto/roboto.html
the server responded with a status of 404 (Not Found)
```

It seems that the only elements linking to `font-roboto/roboto.html` is components from the `iron-demo-helpers` package. Also it seems that font-roboto/roboto.html is not listed in the iron-demo-helper's bower.json file.

The issue is minor. I just thought I should let it be known.

**Comment by maddyjolly2112** [comment]
+1

**Comment by masonlouchart** [comment]
The font Roboto was added in the [v1.2.6](https://github.com/PolymerElements/iron-demo-helpers/releases/tag/v1.2.6) (by the PR #60).
Is it still an issue?

**Comment by mattpalermo** [comment]
@masonlouchart I haven't tested it but that seems like it would solve the problem. I'll close the issue.
