### ISSUE TITLE
Overwrites Component Styles

### ISSUE THREAD

**Issue by cgriffin4** [PolymerElements/iron-demo-helpers#65]
### Description
Importing iron-demo-helpers file causes paper-input to lose style in a component.

### Expected outcome
Paper-input to be rendered correctly

### Actual outcome
Paper-input is missing underline until it's clicked.

### Steps to reproduce
1. Create new 2.0 component
2. Have demo page import demo-pages-shared-styles, demo-snippet, and paper-input
3. Add paper-input tag to body
4. Polymer Serve and view

### Browsers Affected
- [ ] Chrome - Renders Correctly
- [ ] Firefox - Untested
- [ ] Safari 9 - Untested
- [ ] Safari 8 - Untested
- [ ] Safari 7 - Untested
- [ X] Edge
- [ X] IE 11
- [ ] IE 10 - Untested

**Comment by notwaldorf** [comment]
Please provide a reproducible JSBin -- your setup is important, and I can't reproduce this otherwise

**Comment by cgriffin4** [comment]
Closing as this was resolved (I believe it was after I updated polymer-cli or another dependency). Sorry to bother.
