### ISSUE TITLE
Does not work with TypeScript v3  

### ISSUE THREAD

**Issue by hen42** [PolymerElements/iron-demo-helpers#80]
Hi Guys,

the types in demo-snippet.d.ts are incompatible with TypeScript vesion 3-

package.jon:
    @polymer/iron-demo-helpers": "^3.0.2",
    "typescript": "^3.1.3",
 
Output from TypeScript:

/node_modules/@polymer/iron-demo-helpers/demo-snippet.d.ts(51,11): error TS2320: Interface 'DemoSnippetElement'cannot simultaneously extend types 'LegacyElementMixin' and 'HTMLElement'.

  Named property 'toggleAttribute' of types 'LegacyElementMixin' and 'HTMLElement' are not identical.

Best Regards

**Comment by ffendt** [comment]
Hi @hen42,

better late than never: using polymer "^3.2.0" will fix this issue, see [polymer Issue 5372](https://github.com/Polymer/polymer/pull/5372).

Regards

**Comment by hen42** [comment]
Thanks. :)
